multisite_builtin_views.update({
'hostgroupsummary_without_acknowledged_elements': {'browser_reload': 30,
               'column_headers': 'pergroup',
                'datasource': "hostgroups-without-acknowledged-elements",
                'description': _('A short overview over all host groups, without an explicity listing of the actual hosts'),
                'group_painters': [('sitealias', 'sitehosts')],
                'hard_filters': [],
                'hard_filtervars': [],
                'hidden': False,
                'hide_filters': [],
                'layout': 'boxed',
                'mustsearch': False,
                'name': 'hostgroupsummary_without_acknowledged_elements',
                'num_columns': 3,
                'owner': '',
                'painters': [('hg_name', 'hostgroup'),
                             ('hg_alias', None),
                             ('hg_num_hosts_up', None),
                             ('hg_num_hosts_down', None),
                             ('hg_num_hosts_unreach', None),
                             ('hg_num_hosts_pending', None),
                             ('hg_num_services_ok', None),
                             ('hg_num_services_warn', None),
                             ('hg_num_services_crit', None),
                             ('hg_num_services_unknown', None),
                             ('hg_num_services_pending', None)],
                'public': True,
                'show_filters': ['hostgroupnameregex', 'hostgroupvisibility'],
                'sorters': [],
                'title': _('Host Groups (Summary without ackd)'),
                'topic': _('Host Groups') }})
