#!/bin/bash

#
#	Program: 	asterisk_calls
#
#	Purpose:	Check if limit of premium rate calls or international calls is reached.
#			give performance data
#
#	License:	WTFPL (See http://www.wtfpl.net/)
#


RANGE=86400                                     # = 1 day
LOGFILE=/var/log/asterisk/cdr-csv/Master.csv    # Asterisk default cdr logfile
INTERNATIONAL_CRIT=20                           # nr of international calls causing this check to become critical 
PREMIUM_CRIT=1                                  # nr of premium rate  calls causing this check to become critical
THIS_COUNTRY_DIALCODE=49                        # +49 -> Germany
FILTER_AWAY_REGEX="NO_PATTERN_DEFINED"          # Line-RegEx to filter out before counting the numbers

DATE_TO=$(date +"%s")
DATE_FROM=$(( $DATE_TO - $RANGE ))
if [ -f "$LOGFILE" ] ; then
        perl -pe '

        BEGIN {
                        $premium=0;
                        $international=0;
                        $national=0;
                        $status=0;
                        $message="No alerts"
                }

        use Time::Local;
        # this is a little bit ugly because of the format of cdr-file. 
        $rex = qq(("[^",]*"|"""[^"]*""[^"]*"|"[^"]*"),);

        while(<>) {
                next if /'$FILTER_AWAY_REGEX'/;
                /$rex$rex$rex$rex$rex$rex$rex$rex$rex$rex/;
                $target=$3;
                $start=$10;
                $target=~s/"//g;
                $target=~s/\+/00/g;
                ($y,$m,$d,$H,$M,$S) = $start =~ /([0-9]{4})-([0-9]{2})-([0-9]{2}) ([0-9]{2}):([0-9]{2}):([0-9]{2})/;
                $date_epoch = timelocal($S,$M,$H,$d,$m-1,$y);
                if($date_epoch >= '$DATE_FROM' and $date_epoch <= '$DATE_TO') {
                        if($target =~ /^(0900|0190)/)   { $premium++;           next; }
                        if($target =~ /^(0[^0]|00'$THIS_COUNTRY_DIALCODE')/)    { $national++;          next; }
                        if($target =~ /^00/)            { $international++;     next; }

                }
        } 
        END {
                        if($premium       >= '$PREMIUM_CRIT'      ) { 
                                $status = 2; 
                                $message="Critical Count of premium-rate calls reached(Max. '$PREMIUM_CRIT' calls allowed"; }
                        if($international >= '$INTERNATIONAL_CRIT') { 
                                $status = 2; 
                                $message="Critical Count of international calls reached(Max. '$PREMIUM_CRIT' calls allowed"; }
                        printf "%d Asterisk_Calls premium=%d|international=%d|national=%d %s\n", $status, $premium, $international, $national, $message
                }' <$LOGFILE

fi

